version: '3.4'

services:
  msdocspythondjangoazurecontainerappdev:
    image: msdocspythondjangoazurecontainerappdev
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
